import { NextResponse } from 'next/server';

const flights = [
  {
    id: 'f-0',
    flightNumber: 'VN220',
    airline: { name: 'Vietnam Airlines', code: 'VN' },
    origin: 'SGN',
    originName: 'Tan Son Nhat Intl.',
    destination: 'HAN',
    destinationName: 'Noi Bai Intl.',
    status: 'On Time',
    altitude: 36000,
    speed: 872,
    heading: 42,
    aircraft: 'Boeing 787-9',
    registration: 'VN-A879',
    distance: '1,123 km',
    latitude: 16.5,
    longitude: 107.2
  },
  {
    id: 'f-1',
    flightNumber: 'VJ182',
    airline: { name: 'VietJet Air', code: 'VJ' },
    origin: 'SGN',
    originName: 'Tan Son Nhat Intl.',
    destination: 'DAD',
    destinationName: 'Da Nang Intl.',
    status: 'Delayed',
    altitude: 28000,
    speed: 780,
    heading: 15,
    aircraft: 'Airbus A321',
    registration: 'VN-A652',
    distance: '600 km',
    latitude: 13.5,
    longitude: 108.5
  },
  {
    id: 'f-2',
    flightNumber: 'QH902',
    airline: { name: 'Bamboo Airways', code: 'QH' },
    origin: 'HAN',
    originName: 'Noi Bai Intl.',
    destination: 'SGN',
    destinationName: 'Tan Son Nhat Intl.',
    status: 'On Time',
    altitude: 34000,
    speed: 845,
    heading: 195,
    aircraft: 'A320neo',
    registration: 'VN-A588',
    distance: '1,123 km',
    latitude: 18.0,
    longitude: 106.0
  },
  {
    id: 'f-3',
    flightNumber: 'AK513',
    airline: { name: 'AirAsia', code: 'AK' },
    origin: 'KUL',
    originName: 'Kuala Lumpur Intl.',
    destination: 'SGN',
    destinationName: 'Tan Son Nhat Intl.',
    status: 'On Time',
    altitude: 32000,
    speed: 830,
    heading: 38,
    aircraft: 'A320',
    registration: '9M-AQH',
    distance: '1,020 km',
    latitude: 7.5,
    longitude: 105.5
  },
  {
    id: 'f-4',
    flightNumber: 'SQ178',
    airline: { name: 'Singapore Airlines', code: 'SQ' },
    origin: 'SIN',
    originName: 'Changi Airport',
    destination: 'HAN',
    destinationName: 'Noi Bai Intl.',
    status: 'On Time',
    altitude: 37000,
    speed: 905,
    heading: 340,
    aircraft: 'Boeing 787-10',
    registration: '9V-SCI',
    distance: '2,200 km',
    latitude: 10.0,
    longitude: 108.5
  },
  {
    id: 'f-5',
    flightNumber: 'CX764',
    airline: { name: 'Cathay Pacific', code: 'CX' },
    origin: 'HKG',
    originName: 'Hong Kong Intl.',
    destination: 'SGN',
    destinationName: 'Tan Son Nhat Intl.',
    status: 'On Time',
    altitude: 33000,
    speed: 887,
    heading: 210,
    aircraft: 'A350-900',
    registration: 'B-LQA',
    distance: '1,500 km',
    latitude: 19.5,
    longitude: 110.0
  },
  {
    id: 'f-6',
    flightNumber: 'VN126',
    airline: { name: 'Vietnam Airlines', code: 'VN' },
    origin: 'HAN',
    originName: 'Noi Bai Intl.',
    destination: 'DAD',
    destinationName: 'Da Nang Intl.',
    status: 'On Time',
    altitude: 35000,
    speed: 860,
    heading: 180,
    aircraft: 'Airbus A350-900',
    registration: 'VN-A896',
    distance: '628 km',
    latitude: 19.0,
    longitude: 106.5
  },
  {
    id: 'f-7',
    flightNumber: 'VJ901',
    airline: { name: 'VietJet Air', code: 'VJ' },
    origin: 'DAD',
    originName: 'Da Nang Intl.',
    destination: 'HAN',
    destinationName: 'Noi Bai Intl.',
    status: 'Landing',
    altitude: 8000,
    speed: 420,
    heading: 5,
    aircraft: 'Airbus A321neo',
    registration: 'VN-A699',
    distance: '628 km',
    latitude: 20.2,
    longitude: 106.2
  },
  {
    id: 'f-8',
    flightNumber: 'TG684',
    airline: { name: 'Thai Airways', code: 'TG' },
    origin: 'BKK',
    originName: 'Suvarnabhumi Airport',
    destination: 'SGN',
    destinationName: 'Tan Son Nhat Intl.',
    status: 'On Time',
    altitude: 38000,
    speed: 920,
    heading: 120,
    aircraft: 'Boeing 777-300ER',
    registration: 'HS-TKQ',
    distance: '750 km',
    latitude: 12.0,
    longitude: 104.0
  },
  {
    id: 'f-9',
    flightNumber: 'KE481',
    airline: { name: 'Korean Air', code: 'KE' },
    origin: 'ICN',
    originName: 'Incheon Intl.',
    destination: 'SGN',
    destinationName: 'Tan Son Nhat Intl.',
    status: 'On Time',
    altitude: 40000,
    speed: 935,
    heading: 225,
    aircraft: 'Airbus A330-300',
    registration: 'HL7702',
    distance: '3,500 km',
    latitude: 22.0,
    longitude: 111.0
  }
];

export async function GET() {
  return NextResponse.json(flights);
}
